### ISSUE TITLE
Variable for the Download URL of node_exporter or use an Offline Flag. 

### ISSUE THREAD

**Issue by manuel-held** [jinja2ninja/grafana_stack_collection#2]
Hey, thank you for writing this cool Roles. Some of my Servers don't have Internet Access so i have to use a internal Repository Server to fetch the tar.gz or use Ansible to push the Binary to the Server. I would be nice if this Roles support this.

**Comment by manuel-held** [comment]
Wow thank you for the fast response!

**Comment by jinja2ninja** [comment]
No problem! Hopefully that works out for you, I added a new release 1.1.1 with the changes to Ansible Galaxy
