### ISSUE TITLE
Further templatize promtail.yml.j2

### ISSUE THREAD

**Issue by rplevka** [jinja2ninja/grafana_stack_collection#4]
Hi!
It would be nice if more things were templatized in the promtail confing, e.g.:

- loki instance port
- whole scrape config
- promtail server section

maybe it would be nice to provide ability to pass complete, custom yaml too

**Comment by jinja2ninja** [comment]
Hello, sorry for taking a while to get to this, and thanks for taking the time to create an issue here! I really appreciate any feedback people have, and it makes me happy to see people are actually using this collection.

 I added some extra logic to the promtail config template in the latest release (1.2.1). You should be able to create variables for `custom_server_config`, `custom_scrape_configs` and `loki_port` to customize the things you were asking about. As far as passing complete yaml, I do this on my personal setup by just adding a task in my playbook with the `blockinfile` module. PRs are always welcome if there's something else you'd like to add. Also let me know if you have any questions or issues getting these variables to work.
